<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Sanshu2093" failures="2" tests="23" name="Test" time="19.135" errors="0" timestamp="2024-04-18T07:18:07 IST">
  <testcase classname="testngdemo.Example4" name="testCase1" time="0.011"/>
  <testcase classname="testngdemo.Example4" name="testCase1" time="0.001"/>
  <testcase classname="testngdemo.Example4" name="testCase1" time="0.002"/>
  <testcase classname="testngdemo.Example4" name="testCase1" time="0.001"/>
  <testcase classname="testngdemo.Example4" name="testCase1" time="0.001"/>
  <testcase classname="testngdemo.Example4" name="testCase2" time="2.025">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngdemo.Example4.testCase2() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngdemo.Example4.testCase2() didn't finish within the time-out 2000
at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
at app//testngdemo.Example4.testCase2(Example4.java:17)
at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="testngdemo.Example4" name="testCase4" time="1.016"/>
  <testcase classname="testngdemo.Example5" name="testCase1" time="0.001"/>
  <testcase classname="testngdemo.OrangeHrmPIM" name="testOrangeHrmLogin_NegativeFlow" time="9.071"/>
  <testcase classname="testngdemo.OrangeHrmPIM" name="testOrangeHrmLogin_PositiveFlow" time="6.858"/>
  <testcase classname="testngdemo.Example6" name="signUp" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testngdemo.Example6.signUp(Example6.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- signUp -->
  <testcase classname="testngdemo.Example6" name="login" time="0.0">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="testngdemo.Example6" name="composeEmail" time="0.0">
    <skipped/>
  </testcase> <!-- composeEmail -->
  <testcase classname="testngdemo.Example6" name="checkDraft" time="0.0">
    <skipped/>
  </testcase> <!-- checkDraft -->
  <testcase classname="testngdemo.Example6" name="checkSentItems" time="0.0">
    <skipped/>
  </testcase> <!-- checkSentItems -->
  <testcase classname="testngdemo.Example1" name="testcase1" time="0.003"/>
  <testcase classname="testngdemo.Example2" name="testcase1" time="0.001"/>
  <testcase classname="testngdemo.Example2" name="testcase2" time="0.001"/>
  <testcase classname="testngdemo.Example2" name="testcase3" time="0.001"/>
  <testcase classname="testngdemo.Example2" name="testcase4" time="0.001"/>
  <testcase classname="testngdemo.Example3" name="testcase4" time="0.001"/>
  <testcase classname="testngdemo.Example3" name="testcase1" time="0.001"/>
  <testcase classname="testngdemo.Example3" name="testcase2" time="0.001"/>
  <testcase classname="testngdemo.Example4" name="testCase3" time="0.0">
    <ignored/>
  </testcase> <!-- testCase3 -->
  <testcase classname="testngdemo.Example3" name="testcase3" time="0.0">
    <ignored/>
  </testcase> <!-- testcase3 -->
</testsuite> <!-- Test -->
